### ISSUE TITLE
[BUG REPORT] Pages missing on site

### ISSUE THREAD

**Issue by KendallDoesCoding** [krishguptadev/krishguptadev.tech#4]
The contact, about, skills and projects page listed on your website is missing: 

Contact Page: https://www.krishguptadev.tech/contact
About Page: https://www.krishguptadev.tech/about
Skills Page: https://www.krishguptadev.tech/skills
Projects Page: https://www.krishguptadev.tech/projects

**Comment by suitupstan** [comment]
This site is not yet made?

**Comment by KendallDoesCoding** [comment]
> This site is not yet made?

Oh ok, Sorry
